# 04 · Recogidas opcionales (OpenStreetMap)

Recogidas extra, separadas del resto porque cada una tarda bastante:

1. **Competencia:** bordadoras, imprentas, copisterías y tiendas de deporte y de ropa.
2. **Empresas como clientes (oferta Trabajo):** restaurantes, cafés, hoteles e instituciones sociales.
3. **Gráficas, estampagem y bordados buscados por nombre** (OpenStreetMap).
4. **INE:** prueba de si publica las gráficas y la confección por municipio.
5. **Portal BASE:** anuncios de procedimientos.
6. **Clubes:** webs de las asociaciones distritales de fútbol.
7. **Contactos de las cámaras** (CCDR Centro).
8. **Presupuesto del Estado 2026:** lo que recibe cada freguesia.

Se guardan en carpetas propias dentro de `data/raw/` y, como siempre, no se repiten los municipios ya descargados.

> **Cómo leer este notebook.** Antes de cada celda de código hay un bloque **Cómo funciona**: qué hace la celda, por qué se hace así y qué herramientas usa. Cuando algo no se ha visto en clase, se marca como **Nuevo** y se explica con más calma. Las funciones que se llaman (`recoleccion.…`, `cleaning.…`, `analisis.…`) están en la carpeta `src/`, con su explicación en el docstring.

**Cómo funciona**

- **Qué hace:** prepara el notebook. Calcula la carpeta raíz del proyecto, la añade a `sys.path` para poder importar los módulos de `src/`, los recarga y lee `config.yaml` en un diccionario.
- **Por qué así:** el código que se repite vive en `src/` y los valores que pueden cambiar (municipios, URLs, rutas, pesos) en `config.yaml`. Así el notebook solo ordena los pasos. `importlib.reload` vuelve a leer `src/` sin reiniciar el kernel cuando se cambia una función.
- **Herramientas:** `import`, diccionarios, `pathlib.Path` (rutas que funcionan igual en Windows y en Mac).
- **Nuevo (no visto en clase):** `importlib.reload`, `sys.path` y `pathlib`.

In [40]:
import importlib
import sys
from pathlib import Path

import pandas as pd

RAIZ = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.append(str(RAIZ))

from src import recoleccion

# Recarga el código de src/ por si ha cambiado (así no hace falta reiniciar el kernel)
importlib.reload(recoleccion)

config = recoleccion.cargar_config(RAIZ / "config.yaml")
RUTA_RAW = RAIZ / config["rutas"]["raw"]
municipios = [m for lista in config["region"]["distritos"].values() for m in lista]

## 1. Competencia en OpenStreetMap

**Cómo funciona**

- **Qué hace:** pide a Overpass las bordadoras, imprentas, copisterías y tiendas de deporte y de ropa de los 66 municipios.
- **Por qué así:** es la misma función `recoger_osm_region` con otras etiquetas y otra carpeta (`subcarpeta`): el código se reutiliza.
- **Herramientas:** parámetros con nombre, funciones reutilizadas.

In [41]:
competencia_osm = recoleccion.recoger_osm_region(
    municipios, config["overpass"], config["overpass"]["etiquetas_competencia"], RUTA_RAW,
    subcarpeta="overpass_competencia",
)

 1/66 Arganil: 7 elementos
 2/66 Cantanhede: 2 elementos
 3/66 Coimbra: 217 elementos
 4/66 Condeixa-a-Nova: 8 elementos
 5/66 Figueira da Foz: 25 elementos
 6/66 Góis: 0 elementos
 7/66 Lousã: 0 elementos
 8/66 Mira: 3 elementos
 9/66 Miranda do Corvo: 0 elementos
10/66 Montemor-o-Velho: 0 elementos
11/66 Oliveira do Hospital: 2 elementos
12/66 Pampilhosa da Serra: 0 elementos
13/66 Penacova: 0 elementos
14/66 Penela: 0 elementos
15/66 Soure: 4 elementos
16/66 Tábua: 1 elementos
17/66 Vila Nova de Poiares: 0 elementos
18/66 Armamar: 0 elementos
19/66 Carregal do Sal: 1 elementos
20/66 Castro Daire: 0 elementos
21/66 Cinfães: 1 elementos
22/66 Lamego: 0 elementos
23/66 Mangualde: 0 elementos
24/66 Moimenta da Beira: 0 elementos
25/66 Mortágua: 1 elementos
26/66 Nelas: 9 elementos
27/66 Oliveira de Frades: 3 elementos
28/66 Penalva do Castelo: 0 elementos
29/66 Penedono: 0 elementos
30/66 Resende: 0 elementos
31/66 Santa Comba Dão: 0 elementos
32/66 São João da Pesqueira: 0 elementos
33/66 São Pedro do Sul: 1 elementos
34/66 Sátão: 2 elementos
35/66 Sernancelhe: 0 elementos
36/66 Tabuaço: 0 elementos
37/66 Tarouca: 3 elementos
38/66 Tondela: 8 elementos
39/66 Vila Nova de Paiva: 3 elementos
40/66 Viseu: 100 elementos
41/66 Vouzela: 1 elementos
42/66 Aguiar da Beira: 0 elementos
43/66 Almeida: 1 elementos
44/66 Celorico da Beira: 0 elementos
45/66 Figueira de Castelo Rodrigo: 1 elementos
46/66 Fornos de Algodres: 0 elementos
47/66 Gouveia: 2 elementos
48/66 Guarda: 13 elementos
49/66 Manteigas: 1 elementos
50/66 Mêda: 0 elementos
51/66 Pinhel: 1 elementos
52/66 Sabugal: 1 elementos
53/66 Seia: 4 elementos
54/66 Trancoso: 0 elementos
55/66 Vila Nova de Foz Côa: 0 elementos
56/66 Belmonte: 4 elementos
57/66 Castelo Branco: 18 elementos
58/66 Covilhã: 21 elementos
59/66 Fundão: 3 elementos
60/66 Idanha-a-Nova: 0 elementos
61/66 Oleiros: 0 elementos
62/66 Penamacor: 0 elementos
63/66 Proença-a-Nova: 0 elementos
64/66 Sertã: 4 elementos
65/66 Vila de Rei: 0 elementos
66/66 Vila Velha de Ródão: 0 elementos

## 2. Empresas como clientes (oferta Trabajo)

**Cómo funciona**

- **Qué hace:** pide restaurantes, cafés, hoteles e instituciones sociales: posibles clientes de la oferta Trabajo.
- **Por qué así:** misma función, otras etiquetas y otra carpeta.
- **Herramientas:** parámetros con nombre.

In [42]:
trabajo_osm = recoleccion.recoger_osm_region(
    municipios, config["overpass"], config["overpass"]["etiquetas_trabajo"], RUTA_RAW,
    subcarpeta="overpass_trabajo",
)

 1/66 Arganil: 74 elementos
 2/66 Cantanhede: 53 elementos
 3/66 Coimbra: 627 elementos
 4/66 Condeixa-a-Nova: 38 elementos
 5/66 Figueira da Foz: 212 elementos
 6/66 Góis: 23 elementos
 7/66 Lousã: 70 elementos
 8/66 Mira: 36 elementos
 9/66 Miranda do Corvo: 14 elementos
10/66 Montemor-o-Velho: 67 elementos
11/66 Oliveira do Hospital: 101 elementos
12/66 Pampilhosa da Serra: 30 elementos
13/66 Penacova: 22 elementos
14/66 Penela: 22 elementos
15/66 Soure: 44 elementos
16/66 Tábua: 28 elementos
17/66 Vila Nova de Poiares: 17 elementos
18/66 Armamar: 29 elementos
19/66 Carregal do Sal: 24 elementos
20/66 Castro Daire: 47 elementos
21/66 Cinfães: 47 elementos
22/66 Lamego: 53 elementos
23/66 Mangualde: 17 elementos
24/66 Moimenta da Beira: 16 elementos
25/66 Mortágua: 13 elementos
26/66 Nelas: 24 elementos
27/66 Oliveira de Frades: 31 elementos
28/66 Penalva do Castelo: 7 elementos
29/66 Penedono: 9 elementos
30/66 Resende: 10 elementos
31/66 Santa Comba Dão: 22 elementos
32/66 São João da Pesqueira: 25 elementos
33/66 São Pedro do Sul: 42 elementos
34/66 Sátão: 5 elementos
35/66 Sernancelhe: 23 elementos
36/66 Tabuaço: 13 elementos
37/66 Tarouca: 26 elementos
38/66 Tondela: 55 elementos
39/66 Vila Nova de Paiva: 28 elementos
40/66 Viseu: 384 elementos
41/66 Vouzela: 27 elementos
42/66 Aguiar da Beira: 13 elementos
43/66 Almeida: 42 elementos
44/66 Celorico da Beira: 23 elementos
45/66 Figueira de Castelo Rodrigo: 29 elementos
46/66 Fornos de Algodres: 19 elementos
47/66 Gouveia: 46 elementos
48/66 Guarda: 98 elementos
49/66 Manteigas: 31 elementos
50/66 Mêda: 27 elementos
51/66 Pinhel: 30 elementos
52/66 Sabugal: 43 elementos
53/66 Seia: 94 elementos
54/66 Trancoso: 25 elementos
55/66 Vila Nova de Foz Côa: 34 elementos
56/66 Belmonte: 24 elementos
57/66 Castelo Branco: 166 elementos
58/66 Covilhã: 137 elementos
59/66 Fundão: 97 elementos
60/66 Idanha-a-Nova: 44 elementos
61/66 Oleiros: 28 elementos
62/66 Penamacor: 20 elementos
63/66 Proença-a-Nova: 13 elementos
64/66 Sertã: 47 elementos
65/66 Vila de Rei: 6 elementos
66/66 Vila Velha de Ródão: 19 elementos

## 3. Gráficas, estampagem y bordados, buscados por nombre

Con las etiquetas de OpenStreetMap no aparece ninguna bordadora ni imprenta en la región. Aquí se busca por el nombre entre tiendas, talleres, oficinas, industrias y edificios: «Gráfica», «Tipografia», «Serigrafia», «Estamparia», «Bordados», «Personalização», «Publicidade», etc. (el patrón está en `config.yaml`). Tarda unos 15 a 20 minutos.

**Cómo funciona**

- **Qué hace:** busca por el nombre («Gráfica», «Estamparia», «Bordados»…) entre tiendas, talleres, oficinas, industrias y edificios.
- **Por qué así:** con las etiquetas no salía ninguna. `construir_consulta=` pasa otra función como parámetro: la misma recogida, con otra consulta. El patrón es una expresión regular (`,i` = sin distinguir mayúsculas).
- **Herramientas:** funciones como parámetros.
- **Nuevo (no visto en clase):** expresiones regulares dentro de Overpass QL.

In [ ]:
graficas_osm = recoleccion.recoger_osm_region(
    municipios, config["overpass"], config["overpass"]["patron_graficas"], RUTA_RAW,
    subcarpeta="overpass_graficas", construir_consulta=recoleccion.construir_consulta_por_nombre,
)

 1/66 Arganil: 1 elementos
 2/66 Cantanhede: 0 elementos
 3/66 Coimbra: 7 elementos
 4/66 Condeixa-a-Nova: 0 elementos
 5/66 Figueira da Foz: 0 elementos
 6/66 Góis: 0 elementos
 7/66 Lousã: 0 elementos
 8/66 Mira: 0 elementos
 9/66 Miranda do Corvo: 0 elementos
10/66 Montemor-o-Velho: 0 elementos
11/66 Oliveira do Hospital: 2 elementos
12/66 Pampilhosa da Serra: 0 elementos
13/66 Penacova: 0 elementos
14/66 Penela: 0 elementos
15/66 Soure: 0 elementos
16/66 Tábua: 0 elementos
17/66 Vila Nova de Poiares: 0 elementos
18/66 Armamar: 0 elementos
19/66 Carregal do Sal: 0 elementos
20/66 Castro Daire: 0 elementos
21/66 Cinfães: 0 elementos
22/66 Lamego: 0 elementos
23/66 Mangualde: 0 elementos
24/66 Moimenta da Beira: 0 elementos
25/66 Mortágua: 0 elementos
26/66 Nelas: 1 elementos
27/66 Oliveira de Frades: 0 elementos
28/66 Penalva do Castelo: 0 elementos
29/66 Penedono: 0 elementos
30/66 Resende: 0 elementos
31/66 Santa Comba Dão: 0 elementos
32/66 São João da Pesqueira: 0 elementos
33/66 São Pedro do Sul: 0 elementos
34/66 Sátão: 0 elementos
35/66 Sernancelhe: 0 elementos
36/66 Tabuaço: 0 elementos
37/66 Tarouca: 1 elementos
38/66 Tondela: 0 elementos
39/66 Vila Nova de Paiva: 0 elementos
40/66 Viseu: 0 elementos
41/66 Vouzela: 0 elementos
42/66 Aguiar da Beira: 0 elementos
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: sin respuesta, pruebo el siguiente servidor
   maps.mail.ru: error 504, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 1: espero 15 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: error 504, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 2: espero 30 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 3: espero 45 s.
   overpass-api.de: la consulta se quedó sin tiempo, pruebo el siguiente servidor
   overpass.private.coffee: sin respuesta, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 4: espero 60 s.
43/66 Almeida: FALLO, se intentará en la próxima ejecución
44/66 Celorico da Beira: 0 elementos
45/66 Figueira de Castelo Rodrigo: 0 elementos
46/66 Fornos de Algodres: 0 elementos
47/66 Gouveia: 0 elementos
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: sin respuesta, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 1: espero 15 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 2: espero 30 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: sin respuesta, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 3: espero 45 s.
   overpass-api.de: la consulta se quedó sin tiempo, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 4: espero 60 s.
48/66 Guarda: FALLO, se intentará en la próxima ejecución
49/66 Manteigas: 0 elementos
50/66 Mêda: 0 elementos
   overpass-api.de: la consulta se quedó sin tiempo, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 1: espero 15 s.
   overpass-api.de: la consulta se quedó sin tiempo, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 2: espero 30 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: error 504, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 3: espero 45 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor

**Cómo funciona**

- **Qué hace:** repite la búsqueda solo para los municipios grandes que no respondieron a tiempo, dando más tiempo al servidor.
- **Por qué así:** `{**dict, clave: valor}` crea una copia del diccionario con dos valores cambiados; el `config` original no se toca.
- **Herramientas:** diccionarios.
- **Nuevo (no visto en clase):** desempaquetar un diccionario con `**`.

In [ ]:
# Los municipios grandes (Guarda, Covilhã, Castelo Branco...) no caben en 40 s de consulta.
# Se repite solo para los que faltan, con 90 s de consulta y 120 s de espera de respuesta.
# {**dict, clave: valor} crea una copia del diccionario con esos valores cambiados (el config no se toca)
config_lenta = {**config["overpass"], "timeout_consulta": 90, "timeout": 120}
graficas_osm = recoleccion.recoger_osm_region(
    municipios, config_lenta, config["overpass"]["patron_graficas"], RUTA_RAW,
    subcarpeta="overpass_graficas", construir_consulta=recoleccion.construir_consulta_por_nombre,
)

 1/66 Arganil: 1 elementos
 2/66 Cantanhede: 0 elementos
 3/66 Coimbra: 7 elementos
 4/66 Condeixa-a-Nova: 0 elementos
 5/66 Figueira da Foz: 0 elementos
 6/66 Góis: 0 elementos
 7/66 Lousã: 0 elementos
 8/66 Mira: 0 elementos
 9/66 Miranda do Corvo: 0 elementos
10/66 Montemor-o-Velho: 0 elementos
11/66 Oliveira do Hospital: 2 elementos
12/66 Pampilhosa da Serra: 0 elementos
13/66 Penacova: 0 elementos
14/66 Penela: 0 elementos
15/66 Soure: 0 elementos
16/66 Tábua: 0 elementos
17/66 Vila Nova de Poiares: 0 elementos
18/66 Armamar: 0 elementos
19/66 Carregal do Sal: 0 elementos
20/66 Castro Daire: 0 elementos
21/66 Cinfães: 0 elementos
22/66 Lamego: 0 elementos
23/66 Mangualde: 0 elementos
24/66 Moimenta da Beira: 0 elementos
25/66 Mortágua: 0 elementos
26/66 Nelas: 1 elementos
27/66 Oliveira de Frades: 0 elementos
28/66 Penalva do Castelo: 0 elementos
29/66 Penedono: 0 elementos
30/66 Resende: 0 elementos
31/66 Santa Comba Dão: 0 elementos
32/66 São João da Pesqueira: 0 elementos
33/66 São Pedro do Sul: 0 elementos
34/66 Sátão: 0 elementos
35/66 Sernancelhe: 0 elementos
36/66 Tabuaço: 0 elementos
37/66 Tarouca: 1 elementos
38/66 Tondela: 0 elementos
39/66 Vila Nova de Paiva: 0 elementos
40/66 Viseu: 0 elementos
41/66 Vouzela: 0 elementos
42/66 Aguiar da Beira: 0 elementos
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 1: espero 15 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: error 504, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 2: espero 30 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 3: espero 45 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: sin respuesta, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 4: espero 60 s.
43/66 Almeida: FALLO, se intentará en la próxima ejecución
44/66 Celorico da Beira: 0 elementos
45/66 Figueira de Castelo Rodrigo: 0 elementos
46/66 Fornos de Algodres: 0 elementos
47/66 Gouveia: 0 elementos
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: sin respuesta, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 1: espero 15 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: sin respuesta, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 2: espero 30 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: sin respuesta, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 3: espero 45 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: sin respuesta, pruebo el siguiente servidor
   maps.mail.ru: error 504, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 4: espero 60 s.
48/66 Guarda: FALLO, se intentará en la próxima ejecución
49/66 Manteigas: 0 elementos
50/66 Mêda: 0 elementos
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: sin respuesta, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 1: espero 15 s.
   overpass-api.de: la consulta se quedó sin tiempo, pruebo el siguiente servidor
   overpass.private.coffee: sin respuesta, pruebo el siguiente servidor
   maps.mail.ru: error 504, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 2: espero 30 s.
   overpass-api.de: la consulta se quedó sin tiempo, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 3: espero 45 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: error 504, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 4: espero 60 s.
51/66 Pinhel: FALLO, se intentará en la próxima ejecución
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: error 504, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 1: espero 15 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 2: espero 30 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: error 504, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 3: espero 45 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 4: espero 60 s.
52/66 Sabugal: FALLO, se intentará en la próxima ejecución
53/66 Seia: 0 elementos
54/66 Trancoso: 0 elementos
55/66 Vila Nova de Foz Côa: 0 elementos
56/66 Belmonte: 0 elementos
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 1: espero 15 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: error 504, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 2: espero 30 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: sin respuesta, pruebo el siguiente servidor
   maps.mail.ru: error 504, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 3: espero 45 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 4: espero 60 s.
57/66 Castelo Branco: FALLO, se intentará en la próxima ejecución
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: error 504, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 1: espero 15 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: error 504, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 2: espero 30 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: la consulta se quedó sin tiempo, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 3: espero 45 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: error 504, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 4: espero 60 s.
58/66 Covilhã: FALLO, se intentará en la próxima ejecución
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 1: espero 15 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: error 504, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 2: espero 30 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 3: espero 45 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 4: espero 60 s.
59/66 Fundão: FALLO, se intentará en la próxima ejecución
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 1: espero 15 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: error 504, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 2: espero 30 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 3: espero 45 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 4: espero 60 s.
60/66 Idanha-a-Nova: FALLO, se intentará en la próxima ejecución
61/66 Oleiros: 0 elementos
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: error 504, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 1: espero 15 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 2: espero 30 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: error 504, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 3: espero 45 s.
   overpass-api.de: sin respuesta, pruebo el siguiente servidor
   overpass.private.coffee: error 500, pruebo el siguiente servidor
   maps.mail.ru: sin respuesta, pruebo el siguiente servidor
   Ningún servidor disponible. Ronda 4: espero 60 s.
62/66 Penamacor: FALLO, se intentará en la próxima ejecución
63/66 Proença-a-Nova: 0 elementos
64/66 Sertã: 0 elementos
65/66 Vila de Rei: 0 elementos
66/66 Vila Velha de Ródão: 0 elementos

Faltan 9 municipios: ['Almeida', 'Guarda', 'Pinhel', 'Sabugal', 'Castelo Branco', 'Covilhã', 'Fundão', 'Idanha-a-Nova', 'Penamacor']. Vuelve a ejecutar la celda.

## 4. INE: gráficas y confección por municipio (prueba)

El INE no publica las subclases CAE (5 cifras) por municipio. Aquí se comprueba si publica las divisiones (2 cifras) por municipio: la 18 (impresión) y la 14 (industria del vestuario). Primero se leen los metadatos para encontrar los códigos.

**Cómo funciona**

- **Qué hace:** lee los metadatos del indicador de empresas por división y busca los códigos de las divisiones que usamos.
- **Por qué así:** el INE numera las dimensiones (`Dim1`, `Dim3`…); hay que encontrar cuál es la actividad económica. `next(...)` devuelve el primer elemento que cumple la condición.
- **Herramientas:** list comprehension anidada, `startswith`, `pd.DataFrame`.
- **Nuevo (no visto en clase):** `next` con un generador.

In [ ]:
ine = config["ine"]
indicador_div = ine["indicador_empresas_division"]
ruta_meta_div = RUTA_RAW / f"ine_metadatos_{indicador_div}.json"
if not ruta_meta_div.exists():
    recoleccion.guardar_json(recoleccion.pedir_metadatos_ine(indicador_div, ine), ruta_meta_div)
meta_div = recoleccion.leer_json(ruta_meta_div)
meta_div = meta_div[0] if isinstance(meta_div, list) else meta_div
print(meta_div["IndicadorNome"])
print("Último año:", meta_div["UltimoPeriodo"])

# Qué dimensión es la actividad económica y qué códigos tienen las divisiones 18 y 14
dimensiones = meta_div["Dimensoes"]["Descricao_Dim"]
dim_actividad = next(d["dim_num"] for d in dimensiones if d["abrv"].startswith("Atividade"))
categorias = [c for grupo in meta_div["Dimensoes"]["Categoria_Dim"] for lista in grupo.values() for c in lista]
# Las divisiones que usamos están en config.yaml (ine > divisiones_cae)
divisiones = [c for c in categorias if c["dim_num"] == dim_actividad and c["categ_cod"] in ine["divisiones_cae"]]
pd.DataFrame(divisiones)[["categ_cod", "categ_dsg"]]

Empresas (N.º) por Localização geográfica (NUTS - 2013), Atividade económica (Divisão - CAE Rev. 3) e Forma jurídica; Anual - INE, Sistema de contas integradas das empresas
Último año: 2022

  categ_cod                                    categ_dsg
0        14                       Indústria do vestuário
1        18  Impressão e reprodução de suportes gravados
2        55                                   Alojamento
3        56                      Restauração e similares
4        86                   Atividades de saúde humana
5        87    Atividades de apoio social com alojamento
6        88    Atividades de apoio social sem alojamento

**Cómo funciona**

- **Qué hace:** pide los datos de cada división y comprueba si hay dato por municipio (código de 7 caracteres).
- **Por qué así:** era una prueba: si el INE publica las divisiones por municipio, la competencia se puede medir por municipio y no solo por región. Resultado: sí.
- **Herramientas:** set comprehension, `len`, f-strings.

In [ ]:
periodo_div = "S7A" + str(meta_div["UltimoPeriodo"])
respuestas_div = recoleccion.recoger_ine_por_categorias(
    indicador_div, [c["categ_cod"] for c in divisiones], ine, periodo_div, RUTA_RAW,
    dimension=f"Dim{dim_actividad}",
)

# ¿Hay datos por municipio? En el INE, el código de un municipio tiene 7 caracteres (por ejemplo 16E0603)
for codigo, respuesta in respuestas_div.items():
    primero = respuesta[0] if isinstance(respuesta, list) else respuesta
    registros = [r for lista in primero.get("Dados", {}).values() for r in lista]
    con_dato = {r["geodsg"] for r in registros if len(str(r["geocod"])) == 7}
    print(f"División {codigo}: {len(registros)} registros; municipios con dato: {len(con_dato)}")

14: ya estaba guardado
18: ya estaba guardado
55: ya estaba guardado
56: ya estaba guardado
86: ya estaba guardado
87: ya estaba guardado
88: ya estaba guardado
División 14: 1032 registros; municipios con dato: 306
División 18: 1032 registros; municipios con dato: 306
División 55: 1032 registros; municipios con dato: 306
División 56: 1032 registros; municipios con dato: 306
División 86: 1032 registros; municipios con dato: 306
División 87: 1032 registros; municipios con dato: 306
División 88: 1032 registros; municipios con dato: 306

## 5. Portal BASE: anuncios de procedimientos

Los concursos públicos se anuncian antes de adjudicarse y cualquier empresa puede presentarse. Este conjunto de datos (mismo portal, se actualiza cada dos semanas) permite ver cuántos hubo de ropa en la región y, más adelante, vigilar los que estén abiertos.

**Cómo funciona**

- **Qué hace:** lista los archivos del dataset de anuncios del Portal BASE con su tamaño.
- **Por qué así:** igual que con los contratos: antes de descargar se mira qué hay.
- **Herramientas:** `pd.to_numeric`, `sort_values`.

In [ ]:
ruta_info_anuncios = RUTA_RAW / "base_anuncios_info.json"
if ruta_info_anuncios.exists():
    info_anuncios = recoleccion.leer_json(ruta_info_anuncios)
else:
    info_anuncios = recoleccion.listar_recursos_dataset(config["base"]["api_anuncios"])
    recoleccion.guardar_json(info_anuncios, ruta_info_anuncios)

recursos_anuncios = pd.DataFrame(info_anuncios["resources"])
recursos_anuncios["mb"] = (pd.to_numeric(recursos_anuncios["filesize"], errors="coerce") / 1_000_000).round(1)
recursos_anuncios[["title", "format", "mb"]].sort_values("title")

                title format    mb
29  anuncios2012.json   json   5.3
15  anuncios2012.xlsx   xlsx   1.2
28  anuncios2013.json   json   6.6
14  anuncios2013.xlsx   xlsx   1.6
27  anuncios2014.json   json   7.2
13  anuncios2014.xlsx   xlsx   1.7
26  anuncios2015.json   json   7.2
12  anuncios2015.xlsx   xlsx   1.8
25  anuncios2016.json   json   8.1
11  anuncios2016.xlsx   xlsx   2.0
24  anuncios2017.json   json  10.6
10  anuncios2017.xlsx   xlsx   2.5
23  anuncios2018.json   json  10.3
9   anuncios2018.xlsx   xlsx   2.4
22  anuncios2019.json   json  12.9
8   anuncios2019.xlsx   xlsx   3.1
21  anuncios2020.json   json  15.4
7   anuncios2020.xlsx   xlsx   3.5
20  anuncios2021.json   json  16.4
6   anuncios2021.xlsx   xlsx   3.8
19  anuncios2022.json   json  18.0
5   anuncios2022.xlsx   xlsx   4.1
18  anuncios2023.json   json  25.3
4   anuncios2023.xlsx   xlsx   5.7
17  anuncios2024.json   json  24.2
3   anuncios2024.xlsx   xlsx   5.9
16  anuncios2025.json   json  30.9
2   anuncios2025.xlsx   xlsx   8.1
0   anuncios2026.json   json  22.5
1   anuncios2026.xlsx   xlsx   5.9

**Cómo funciona**

- **Qué hace:** descarga el archivo de anuncios de cada año, en Excel si existe y, si no, en CSV.
- **Por qué así:** `sort_values(key=...)` pone primero el Excel; `continue` salta los años sin archivo; `if ruta.exists()` evita descargar dos veces.
- **Herramientas:** filtros con `&`, `isin`, `iloc`, `continue`.
- **Nuevo (no visto en clase):** `sort_values` con `key`.

In [ ]:
# Descarga de los anuncios de los años elegidos (en Excel si existe; si no, en CSV)
for ano in config["base"]["anos"]:
    candidatos = recursos_anuncios[
        recursos_anuncios["title"].str.contains(str(ano))
        & recursos_anuncios["format"].str.lower().isin(["xlsx", "csv"])
    ].sort_values("format", key=lambda formato: formato.str.lower() != "xlsx")
    if candidatos.empty:
        print(ano, ": no hay ningún archivo con ese año en el título")
        continue
    fila = candidatos.iloc[0]
    nombre = fila["title"] if "." in fila["title"] else f"{fila['title']}.{fila['format'].lower()}"
    ruta = RUTA_RAW / "base_anuncios" / nombre
    if ruta.exists():
        print(nombre, "ya estaba descargado")
    else:
        print("Descargando", nombre, fila["mb"], "MB")
        recoleccion.descargar_archivo(fila["url"], ruta)

anuncios2020.xlsx ya estaba descargado
anuncios2021.xlsx ya estaba descargado
anuncios2022.xlsx ya estaba descargado
anuncios2023.xlsx ya estaba descargado
anuncios2024.xlsx ya estaba descargado
anuncios2025.xlsx ya estaba descargado

## 6. Clubes: ¿publican las asociaciones distritales de fútbol la lista de sus clubes?

Primero se comprueba el robots.txt y se guardan la portada y las páginas que hablan de clubes para revisarlas.

**Resultado:** las webs de Viseu, Guarda y Castelo Branco devolvieron error, y en la de Coimbra las páginas de clubes dieron error o el robots.txt no las permite. No se insiste: el plan B son los futbolistas federados por distrito del INE (sección 9).

**Cómo funciona**

- **Qué hace:** comprueba el robots.txt de las webs de las asociaciones distritales de fútbol, descarga la portada y busca enlaces que hablen de clubes.
- **Por qué así:** el robots.txt dice qué páginas permite descargar un sitio: si no lo permite, no se descarga. `try/except` sigue con el siguiente distrito si una web falla.
- **Herramientas:** `try/except`, `continue`, `BeautifulSoup` (dentro de `enlaces_con_palabras`).
- **Nuevo (no visto en clase):** `urllib.robotparser` (lector de robots.txt).

In [ ]:
import time

web = config["web"]
carpeta_clubes = RUTA_RAW / "clubes"
enlaces_af = {}
for distrito, url in web["asociaciones_futbol"].items():
    ruta = carpeta_clubes / f"af_{recoleccion.nombre_en_url(distrito)}.html"
    try:
        if not ruta.exists() and not recoleccion.permitido_por_robots(url, web["user_agent"]):
            print(distrito, ": el robots.txt no permite descargar la página")
            continue
        html = recoleccion.descargar_html(url, ruta, web["user_agent"])
    except Exception as error:
        print(distrito, ": no se pudo descargar", type(error).__name__)
        continue
    enlaces_af[distrito] = recoleccion.enlaces_con_palabras(html, url, ["clube", "filiad", "associad"])
    print(f"{distrito}: {len(enlaces_af[distrito])} enlaces sobre clubes")
recoleccion.guardar_json(enlaces_af, carpeta_clubes / "enlaces_af.json")

Coimbra: 4 enlaces sobre clubes
Viseu: 1 enlaces sobre clubes
Guarda: 0 enlaces sobre clubes
Castelo Branco : no se pudo descargar HTTPError

WindowsPath('c:/Users/Asus/Desktop/65_DATA_ANALYTICS_IRONHACK/data-wrangling-project/data/raw/clubes/enlaces_af.json')

**Cómo funciona**

- **Qué hace:** guarda las 5 primeras páginas sobre clubes de cada asociación, respetando el robots.txt y con una pausa entre peticiones.
- **Por qué así:** se guardan para revisarlas a mano antes de decidir si se pueden extraer los clubes.
- **Herramientas:** `enumerate(start=1)`, slicing, `try/except`, `time.sleep`.

In [ ]:
# Se guardan las primeras 5 páginas sobre clubes de cada asociación, para revisarlas
for distrito, enlaces in enlaces_af.items():
    for numero, enlace in enumerate(enlaces[:5], start=1):
        es_pdf = enlace["url"].lower().endswith(".pdf")
        ruta = carpeta_clubes / f"af_{recoleccion.nombre_en_url(distrito)}_{numero}.{'pdf' if es_pdf else 'html'}"
        if ruta.exists():
            continue
        try:
            if not recoleccion.permitido_por_robots(enlace["url"], web["user_agent"]):
                print(distrito, numero, ": no permitido por el robots.txt")
                continue
            if es_pdf:
                recoleccion.descargar_archivo(enlace["url"], ruta)
            else:
                recoleccion.descargar_html(enlace["url"], ruta, web["user_agent"])
            time.sleep(web["pausa_segundos"])
        except Exception as error:
            print(distrito, numero, ": no se pudo descargar", type(error).__name__)
print("Archivos guardados:", len(list(carpeta_clubes.glob("af_*"))))

Viseu 1 : no se pudo descargar HTTPError
Archivos guardados: 7

## 7. Contactos de las cámaras (CCDR Centro)

La CCDR Centro tiene una página de contacto por municipio (solo de la región Centro).

**Resultado:** el robots.txt no permite descargarlas, así que no se descarga nada. El contacto de las cámaras se busca en su web oficial.

**Cómo funciona**

- **Qué hace:** comprueba si el robots.txt de la CCDR Centro permite descargar las páginas de contacto de las cámaras y, solo si lo permite, las descarga.
- **Por qué así:** no lo permite, así que no se descarga nada. Es una decisión ética: no se buscan rodeos.
- **Herramientas:** `if`, `format` en una URL, `try/except`.

In [ ]:
import time

web = config["web"]
permitido = recoleccion.permitido_por_robots(web["url_contactos_ccdrc"].format(nombre="tabua"), web["user_agent"])
print("¿Lo permite el robots.txt?", permitido)

if permitido:
    sin_pagina = []
    for municipio in municipios:
        nombre = recoleccion.nombre_en_url(municipio)
        ruta = RUTA_RAW / "contactos_ccdrc" / f"{nombre}.html"
        if ruta.exists():
            continue
        try:
            recoleccion.descargar_html(web["url_contactos_ccdrc"].format(nombre=nombre), ruta, web["user_agent"])
            time.sleep(web["pausa_segundos"])
        except Exception:
            sin_pagina.append(municipio)
    print("Municipios sin página en la CCDR Centro:", sin_pagina)

¿Lo permite el robots.txt? False

## 8. Presupuesto del Estado 2026: lo que recibe cada freguesia

La Lei 73-A/2025 (OE2026) debía incluir el Fondo de Financiación de las Freguesias de cada una, para medir el tamaño de cada junta.

**Resultado:** el PDF se descargó, pero ese mapa no viene en él; el que sí se pudo leer (transferencia de competencias, DL 57/2019) solo cubre 37 de los 66 municipios. Se descartó y se explica en el README.

**Cómo funciona**

- **Qué hace:** descarga el PDF de la ley del Presupuesto del Estado 2026, si el robots.txt lo permite.
- **Por qué así:** se buscaba el dinero que recibe cada freguesia para medir el tamaño de cada junta.
- **Herramientas:** `Path.stat().st_size`, `round`.

In [ ]:
web = config["web"]
ruta_oe = RUTA_RAW / "oe2026" / "lei-73-a-2025.pdf"
if not ruta_oe.exists():
    if recoleccion.permitido_por_robots(web["url_oe2026"], web["user_agent"]):
        recoleccion.descargar_archivo(web["url_oe2026"], ruta_oe)
    else:
        print("El robots.txt no permite descargar el PDF")
if ruta_oe.exists():
    print("OE2026 descargado:", round(ruta_oe.stat().st_size / 1_000_000, 1), "MB")

OE2026 descargado: 24.8 MB

## 9. INE: futbolistas inscritos en la Federación, por distrito

OpenStreetMap casi no registra clubes. Este indicador (INE, a partir de la FPF) da el número de futbolistas inscritos por distrito: no dice qué clubes hay, pero sí cuánta actividad de clubes hay en cada distrito.

**Cómo funciona**

- **Qué hace:** pide los futbolistas inscritos en la Federación por distrito (INE).
- **Por qué así:** es el plan B para los clubes: no dice qué clubes hay, pero sí cuánta actividad de clubes hay en cada distrito.
- **Herramientas:** patrón de caché, `.get()`.

In [ ]:
ine = config["ine"]
ruta_futbolistas = RUTA_RAW / f"ine_{ine['indicador_futbolistas']}.json"
if not ruta_futbolistas.exists():
    recoleccion.guardar_json(recoleccion.pedir_datos_ine(ine["indicador_futbolistas"], ine), ruta_futbolistas)
datos_futbolistas = recoleccion.leer_json(ruta_futbolistas)
primero = datos_futbolistas[0] if isinstance(datos_futbolistas, list) else datos_futbolistas
for periodo, registros in primero.get("Dados", {}).items():
    print(periodo, "- registros:", len(registros))

2024 - registros: 66